# Dagger workspace configuration
# Install modules with: dagger module install <module>
# Example:
#   dagger module install github.com/dagger/dagger/modules/wolfi

[modules]

[modules.python-sdk]
source = "dagger.io/sdk/python"

[sdks.python]
module = "python-sdk"

[sdks.python.scopes.my-module]
is-module = true
name = "my-module"

[sdks.python.scopes.my-module.settings]
dangEntrypoint = true
